name: CD

on:
  release:
    types: [created, released]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (or another Docker registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Set this in your repo's secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Set this in your repo's secrets

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker image with cache
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/real-backend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
