name: CI

on:
  push:
    branches:
      - master
jobs:
  styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ruff Format
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check 
        
      - name: Ruff Check
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github
  tests:
    needs: styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          SECRET_KEY: "test_secret"
          ALGORITHM: "HS256"
          ACCESS_TOKEN_EXPIRE_MINUTES: "30"
          ALLOWED_ORIGIN: "http://localhost:3000"
          DB_URL: "sqlite:///test.db"
        run: uv run -m pytest tests